language: node_js
node_js:
  - "0.10"

before_script:
  - sudo apt-get install curl

script:
  - ACCESS_TOKEN=fd958309d7924453a2f257069881d9ba
  - ENVIRONMENT=marlene_test
  - LOCAL_USERNAME=`whoami`
  - REVISION=`git log -n 1 --pretty=format:"%H"`
  - curl "https://api.rollbar.com/api/1/deploy/" -F access_token=$ACCESS_TOKEN -F environment=$ENVIRONMENT -F revision=$REVISION -F local_username=$LOCAL_USERNAME
